version: '2'
services:
    cuidebemapp-app:
        image: cuidebemapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cuidebemapp-postgresql:5432/cuidebemapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cuidebemapp-postgresql:
        extends:
            file: postgresql.yml
            service: cuidebemapp-postgresql
